name: Azure Static Webapp build and deploy

on:
  push:
    branches:
      - azure
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - azure

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: nkvch-omen-ubuntu22
    name: Build and Deploy Job
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          nvm use 18
          npm install -g yarn
          npm install -g @azure/static-web-apps-cli
          yarn install

      - name: Build and deploy
        run: |
          swa build
          swa deploy -T ${{ secrets.AZURE_TENANT_ID }} -S ${{ secrets.AZURE_SUBSCRIPTION_ID }} -d ${{ secrets.AZURE_STATIC_WEB_APPS_DEPLOYMENT_TOKEN}} --env production
